package com.example.ballrunbot;
import android.app.*;import android.content.*;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.MediaProjection;import android.app.ServiceInfo;import android.os.*;import java.util.concurrent.atomic.AtomicBoolean;
public class BallRunCaptureService extends Service{
 private MediaProjection projection;private ImageReader reader;private VirtualDisplay display;private SharedPreferences prefs;private long frames=0,lastProcess=0;private final AtomicBoolean busy=new AtomicBoolean(false);
 @Override public void onCreate(){super.onCreate();prefs=getSharedPreferences("bot",MODE_PRIVATE);createChannel();}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel("capture","Ball Run Bot",NotificationManager.IMPORTANCE_LOW));}
 private Notification notification(String t){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,"capture"):new Notification.Builder(this);return b.setContentTitle("Ball Run Bot").setContentText(t).setSmallIcon(android.R.drawable.ic_media_play).setOngoing(true).build();}
 @Override public int onStartCommand(Intent in,int flags,int id){if(in==null)return START_NOT_STICKY;int rc=in.getIntExtra("resultCode",Activity.RESULT_CANCELED);Intent data=in.getParcelableExtra("data");if(rc!=Activity.RESULT_OK||data==null){fail("Capture permission missing");return START_NOT_STICKY;}if(Build.VERSION.SDK_INT>=29)startForeground(10,notification("Screen capture active"),ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION);else startForeground(10,notification("Screen capture active"));setupProjection(data,rc);return START_NOT_STICKY;}
 private void fail(String msg){prefs.edit().putBoolean("capture_active",false).putBoolean("bot_running",false).putString("command","NONE").putString("vision_detail",msg).apply();stopSelf();}
 private void setupProjection(Intent data,int rc){android.media.projection.MediaProjectionManager m=(android.media.projection.MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=m.getMediaProjection(rc,data);if(projection==null){fail("Capture permission failed");return;}projection.registerCallback(new MediaProjection.Callback(){@Override public void onStop(){fail("Screen capture stopped");}},new Handler(Looper.getMainLooper()));createDisplay();}
 private void createDisplay(){android.util.DisplayMetrics dm=getResources().getDisplayMetrics();int w=dm.widthPixels,h=dm.heightPixels;reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);reader.setOnImageAvailableListener(r->{Image im=null;try{im=r.acquireLatestImage();if(im==null||busy.get())return;busy.set(true);frames++;prefs.edit().putLong("frames",frames).putBoolean("capture_active",true).apply();long now=SystemClock.uptimeMillis();if(now-lastProcess>=140){lastProcess=now;analyze(im,w,h);}}catch(Exception e){prefs.edit().putString("command","NONE").putString("vision_detail","Vision error").apply();}finally{if(im!=null)im.close();busy.set(false);}},new Handler(Looper.getMainLooper()));display=projection.createVirtualDisplay("BallRunBot",w,h,dm.densityDpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,null);}
 private void analyze(Image image,int w,int h){Image.Plane p=image.getPlanes()[0];int pw=image.getWidth(),ph=image.getHeight();java.nio.ByteBuffer buf=p.getBuffer();int row=p.getRowStride(),pix=p.getPixelStride(),step=8;long count=0;float sumX=0;int minY=ph,maxY=0;for(int y=(int)(ph*.35);y<(int)(ph*.94);y+=step){int base=y*row;for(int x=0;x<pw;x+=step){int i=base+x*pix;if(i+3>=buf.limit())continue;int rr=buf.get(i+2)&255,gg=buf.get(i+1)&255,bb=buf.get(i)&255;boolean pink=rr>145&&bb>85&&rr>gg*1.35&&bb>gg*1.15;if(pink){count++;sumX+=x;if(y<minY)minY=y;if(y>maxY)maxY=y;}}}if(count<12){prefs.edit().putString("command","NONE").putString("vision_detail","No confident player").apply();return;}float cx=sumX/count;if((minY+maxY)/2f<ph*.50f){prefs.edit().putString("command","NONE").putString("vision_detail","Player not in safe zone").apply();return;}int upperCount=0;float obstacleX=0;for(int y=(int)(ph*.20);y<(int)(ph*.65);y+=step){int base=y*row;for(int x=0;x<pw;x+=step){int i=base+x*pix;if(i+3>=buf.limit())continue;int rr=buf.get(i+2)&255,gg=buf.get(i+1)&255,bb=buf.get(i)&255;boolean pink=rr>145&&bb>85&&rr>gg*1.35&&bb>gg*1.15;if(pink){upperCount++;obstacleX+=x;}}}if(upperCount<20){prefs.edit().putString("command","NONE").putString("vision_detail","Player found; no obstacle").apply();return;}obstacleX/=upperCount;String cmd="NONE";float margin=Math.max(45,pw*.045f);if(Math.abs(obstacleX-cx)>margin)cmd=obstacleX>cx?"LEFT":"RIGHT";prefs.edit().putString("command",cmd).putString("vision_detail","Ball x="+(int)cx+" obstacle x="+(int)obstacleX).apply();}
 @Override public void onDestroy(){prefs.edit().putBoolean("capture_active",false).putBoolean("bot_running",false).putString("command","NONE").apply();if(display!=null)display.release();if(reader!=null)reader.close();if(projection!=null)projection.stop();super.onDestroy();}
 @Override public android.os.IBinder onBind(Intent i){return null;}
}