package com.example.ballrunbot;
import android.Manifest;import android.app.Activity;import android.content.Intent;import android.content.SharedPreferences;import android.content.pm.PackageManager;import android.media.projection.MediaProjectionManager;import android.os.*;import android.provider.Settings;import android.view.Gravity;import android.widget.*;
public class MainActivity extends Activity{
 private static final int CAPTURE_REQUEST=1001;private SharedPreferences prefs;private TextView status;private final Handler handler=new Handler();
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("bot",MODE_PRIVATE);stopBot();buildUi();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7);handler.post(refresh);}
 private void buildUi(){ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(40,50,40,40);box.setGravity(Gravity.CENTER_HORIZONTAL);TextView title=new TextView(this);title.setText("🏎️ BALL RUN BOT");title.setTextSize(28);title.setGravity(Gravity.CENTER);box.addView(title,lp(-1,-2));status=new TextView(this);status.setTextSize(16);status.setPadding(0,25,0,25);box.addView(status,lp(-1,-2));Button cap=button("📱 START SCREEN CAPTURE");cap.setOnClickListener(v->requestCapture());box.addView(cap,lp(-1,60));Button access=button("♿ OPEN ACCESSIBILITY SETTINGS");access.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));box.addView(access,lp(-1,60));Button start=button("▶ START BOT");start.setOnClickListener(v->startBot());box.addView(start,lp(-1,70));Button stop=button("■ STOP BOT");stop.setOnClickListener(v->stopBot());box.addView(stop,lp(-1,70));TextView note=new TextView(this);note.setText("Safety: bot starts OFF. Gestures require active capture + explicit running + fresh LEFT/RIGHT vision. STOP clears the command.");note.setPadding(0,25,0,0);box.addView(note,lp(-1,-2));scroll.addView(box);setContentView(scroll);}
 private Button button(String s){Button b=new Button(this);b.setText(s);return b;} private LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}
 private void requestCapture(){MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);startActivityForResult(m.createScreenCaptureIntent(),CAPTURE_REQUEST);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==CAPTURE_REQUEST&&c==RESULT_OK&&d!=null){Intent s=new Intent(this,BallRunCaptureService.class);s.putExtra("resultCode",c);s.putExtra("data",d);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);}}
 private void startBot(){if(!prefs.getBoolean("capture_active",false)){prefs.edit().putBoolean("bot_running",false).putString("command","NONE").putString("vision_detail","Start screen capture first").apply();return;}prefs.edit().putBoolean("bot_running",true).putString("command","NONE").apply();BallRunAccessibilityService.enableController(true);}
 private void stopBot(){prefs.edit().putBoolean("bot_running",false).putString("command","NONE").apply();BallRunAccessibilityService.enableController(false);}
 private final Runnable refresh=new Runnable(){public void run(){if(status!=null){boolean bot=prefs.getBoolean("bot_running",false),cap=prefs.getBoolean("capture_active",false);status.setText((cap?"🟢 CAPTURE ACTIVE":"⚪ CAPTURE OFF")+"\nFrames: "+prefs.getLong("frames",0)+"\nVision: "+prefs.getString("vision_detail","Waiting for capture")+"\nBot: "+(bot?"🟢 RUNNING":"🔴 STOPPED")+"\nCommand: "+prefs.getString("command","NONE"));}handler.postDelayed(this,500);}};
 @Override protected void onDestroy(){handler.removeCallbacksAndMessages(null);stopBot();super.onDestroy();}
}